version: "3.9"

services:
  ui:
    container_name: icfpc2023-ui
    volumes:
      - ./ui/:/src
      - /src/node_modules   # ignore node_modules
    build:
      context: .
      dockerfile: Dockerfile.ui
    command: pnpm dev:server
    ports:
      - "5173:5173"

  server:
    container_name: icfpc2023-server
    build:
      context: .
      dockerfile: Dockerfile.server
    command: make start-server
    volumes:
      - .:/src
      - /src/ui  # ignore all UI
    ports:
      - "8000:8000"
